### ISSUE TITLE
Speech Commands Dataset

### ISSUE THREAD

**Issue by harritaylor** [audeering/audtorch#48]
### Feature

I'd like to add the google speech commands dataset (https://ai.googleblog.com/2017/08/launching-speech-commands-dataset.html) as `audtorch.datasets.speech_commands.py`, following the code style of `mozille_common_voice.py`, and `libri_speech.py`. Is anyone already working on this or should I go ahead and start? 

### Motivation

More datasets :-)

**Comment by phtephanx** [comment]
Hi @harritaylor,

Thanks for your request!
```
Is anyone already working on this or should I go ahead and start?
```
You're very welcome to add this data set! None of us is working on it.

**Comment by harritaylor** [comment]
Excellent, I'll submit a pull when it's ready. Cheers!

**Comment by harritaylor** [comment]
PR submitted https://github.com/audeering/audtorch/pull/49
