### ISSUE TITLE
Librosa missing from setup.py

### ISSUE THREAD

**Issue by harritaylor** [audeering/audtorch#50]
### Bug

Base environment has requirement librosa for `transforms` but `setup.py` does not install it.

```
AttributeError                            Traceback (most recent call last)

<ipython-input-3-9c3b3e97ee3c> in <module>
      3 
      4 a = np.array([1.,2.,3.,4.,])
----> 5 print(t_s(a))
      6 
      7 mean, std, max = [], [], []

~/Workspace/Repositories/audtorch/audtorch/transforms/transforms.py in __call__(self, signal)
    856         spectrogram = F.stft(signal, self.window_size, self.hop_size,
    857                              fft_size=self.fft_size, window=self.window,
--> 858                              axis=self.axis)
    859         magnitude, self.phase = librosa.magphase(spectrogram)
    860         return magnitude

~/Workspace/Repositories/audtorch/audtorch/transforms/functional.py in stft(signal, window_size, hop_size, fft_size, window, axis)
    339     fft_config = dict(n_fft=fft_size, hop_length=hop_size,
    340                       win_length=window_size, window=window)
--> 341     spectrogram = np.apply_along_axis(librosa.stft, axis, signal, **fft_config)
    342     return spectrogram
    343 

AttributeError: 'NoneType' object has no attribute 'stft'
```

### Steps to reproduce

List of steps/code to reproduce the bug:

1. Create a new, isolated virtual environment
2. Run example code for spectrogram transform
```
>>> a = np.array([1., 2., 3., 4.])
>>> t = Spectrogram(2, 2)
>>> print(t)
Spectrogram(window_size=2, hop_size=2, axis=-1)
```

3. Check virtual environment to see if librosa is installed 
```
>>> import librosa
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'librosa'
```

### Expected behaviour

Result:
```
>>> t(a)
array([[1., 3., 3.],
       [1., 3., 3.]], dtype=float32)
```

### Environment

* OS: MacOS 10.14
* Python version: 3.7
* audtorch version: 0.2.1

**Comment by hagenw** [comment]
Thanks for spotting this. It is for purpose at the moment, compare https://github.com/audeering/audtorch/blob/master/audtorch/transforms/transforms.py#L6-L13.
The idea was as we need `librosa` and `scipy` only for very little parts of `audtorch` to not add them as a dependency.

But you are totally right, the current solution is not ideal. If you don't have it installed there is no useful error message and we also don't mention it in the installation instructions: https://audtorch.readthedocs.io/en/0.2.1/install.html

I see two solutions:

1. Add `librosa` and `scipy` as dependency in `setup.py`
2. Find a meaningful way of providing an error message stating that you have to install them and mention them also as dependencies in the installation instructions.

**Comment by ATriantafyllopoulos** [comment]
Closing as `librosa` is now included in `setup.cfg`: https://github.com/audeering/audtorch/blob/master/setup.cfg
