### ISSUE TITLE
Query: Recommended way to work with Audioset

### ISSUE THREAD

**Issue by tridivb** [audeering/audtorch#53]
### Questions and Help

How does the code fetch the Audioset dataset? Does it work with the extracted features or does it download the actual audio clips? 

I am currently trying to get this to work but everytime I try to run the example code (after configuring the paths and including the csv file) it throws up the error that the ontology.json file is missing. I could not find any section of the code where it automatically downloads the dataset and creates the sub-directories. I assume that we have to do this ourselves. Is this correct?

**Comment by hagenw** [comment]
The `Audioset` class indeed assumes that you have downloaded the data set before and it is stored in the following format:

```
balanced_train_segments/
eval_segments/
unbalanced_train_segments/
balanced_train_segments.csv
eval_segments.csv
ontology.json
unbalanced_train_segments.csv
```

The CSV files can be downloaded at https://research.google.com/audioset/download.html.
The `ontology.json` can be downloaded from https://github.com/audioset/ontology.

**Comment by tridivb** [comment]
Thank you for the confirmation.

**Comment by hagenw** [comment]
The name of the files in the folder look then like this:
```
--i-y1v8Hy8_0.000.wav
-1EXhfqLLwQ_150.000.wav
...
```

Let me know, if you have further questions.
